name: Deploy to S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp . s3://${{ secrets.AWS_S3_BUCKET }} --recursive --exclude ".git/*"
        






# name: Upload to S3
# on:
#   push:
#     branches:
#       - main
# jobs:
#   upload:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Upload to S3
# #         image: python
# #         entrypoint: [""]
#         env:
#           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: |
#           pip install awscli
#           aws configure set region us-east-1
#           aws s3 cp . s3://${{ secrets.AWS_S3_BUCKET }}/DAG/github/ --recursive --debug




# name: Upload to S3
# on:
#   push:
#     branches:
#       - main

# jobs:
#   upload:
#     runs-on: windows-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Install AWS CLI
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y awscli

#     - name: Upload to S3
#       run: |
#         aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --delete
#       env:
#         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
